Parameterize deb build process
Customize control file based on compiling host

diff --git a/build b/build
--- a/build
+++ b/build
@@ -84,6 +84,13 @@ fi
 
 if [ x$1 = "xdebian" ]; then
   here=`pwd`
+  version=`cat $here/VERSION`
+  arch=`uname -m`
+  case "$arch" in
+    arm*) arch=armhf;;
+    aarch64*) arch=arm64;;
+    *) echo "FATAL ERROR: Unknown architecture $arch"; exit 1;;
+  esac
   cd debian-template/wiringPi
   rm -rf usr
   cd $here/wiringPi
@@ -93,8 +100,9 @@ if [ x$1 = "xdebian" ]; then
   cd $here/gpio
   make install-deb INCLUDE='-I../wiringPi -I../devLib' LDFLAGS=-L../debian-template/wiringPi/usr/lib
   cd $here/debian-template
+  sed -e "s/%%VERSION%%/${version}/" -e "s/%%ARCH%%/${arch}/" < wiringPi/DEBIAN/control.template > wiringPi/DEBIAN/control
   fakeroot dpkg-deb --build wiringPi
-  mv wiringPi.deb  wiringpi-`cat $here/VERSION`-1.deb
+  mv wiringPi.deb  wiringpi-"${version}"-1.deb
   exit
 fi
 
